repos:
#
# If your package has useful API documentation you can uncomment this so it's automatically updated
# whenever you commit
# 
#-   repo: local
    #hooks:
    #-   id: api_docs_gen
        #name: API Docs Gen
        #language: system
        #entry: sphinx-apidoc --separate --force --no-toc --implicit-namespaces src/pds -o docs/src/api
        #pass_filenames: false

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer

-   repo: https://github.com/asottile/reorder_python_imports
    rev: v2.2.0
    hooks:
    -   id: reorder-python-imports

-   repo: local
    hooks:
    -   id: mypy
        name: mypy
        entry: mypy src
        language: system
        types: [python]
        pass_filenames: false

-   repo: local
    hooks:
    -   id: black
        name: black
        entry: black src
        language: system
        pass_filenames: false

-   repo: local
    hooks:
    -   id: lint
        name: flake8
        entry: flake8 src
        language: system
        types: [python]
        pass_filenames: false

-   repo: local
    hooks:
    -   id: tests
        name: Tests
        entry: pytest
        language: system
        stages: [push]
        pass_filenames: false
