---

name: 🤔 Description

on:
    push:
        branches:
            -   master

jobs:
    description:
        name: 📣 Description
        runs-on: ubuntu-latest
        steps:
            -
                name: 💳 Checkout
                uses: actions/checkout@v2
                with:
                    lfs: true
                    token: ${{secrets.ADMIN_GITHUB_TOKEN}}
            -
                name: 🔎 💢
                run: |
                    ls -laF
                    git tag --list
                    git branch --list
                    git describe --tags

...


# -*- mode: yaml; indent: 4; fill-column: 120; coding: utf-8 -*-
